// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.1
// source: recordserver/record_server.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RecordServerClient is the client API for RecordServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RecordServerClient interface {
	Record(ctx context.Context, in *RecordRequest, opts ...grpc.CallOption) (*RecordResponse, error)
}

type recordServerClient struct {
	cc grpc.ClientConnInterface
}

func NewRecordServerClient(cc grpc.ClientConnInterface) RecordServerClient {
	return &recordServerClient{cc}
}

func (c *recordServerClient) Record(ctx context.Context, in *RecordRequest, opts ...grpc.CallOption) (*RecordResponse, error) {
	out := new(RecordResponse)
	err := c.cc.Invoke(ctx, "/record_server.RecordServer/Record", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecordServerServer is the server API for RecordServer service.
// All implementations must embed UnimplementedRecordServerServer
// for forward compatibility
type RecordServerServer interface {
	Record(context.Context, *RecordRequest) (*RecordResponse, error)
	mustEmbedUnimplementedRecordServerServer()
}

// UnimplementedRecordServerServer must be embedded to have forward compatible implementations.
type UnimplementedRecordServerServer struct {
}

func (UnimplementedRecordServerServer) Record(context.Context, *RecordRequest) (*RecordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Record not implemented")
}
func (UnimplementedRecordServerServer) mustEmbedUnimplementedRecordServerServer() {}

// UnsafeRecordServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RecordServerServer will
// result in compilation errors.
type UnsafeRecordServerServer interface {
	mustEmbedUnimplementedRecordServerServer()
}

func RegisterRecordServerServer(s grpc.ServiceRegistrar, srv RecordServerServer) {
	s.RegisterService(&RecordServer_ServiceDesc, srv)
}

func _RecordServer_Record_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordServerServer).Record(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/record_server.RecordServer/Record",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordServerServer).Record(ctx, req.(*RecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RecordServer_ServiceDesc is the grpc.ServiceDesc for RecordServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RecordServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "record_server.RecordServer",
	HandlerType: (*RecordServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Record",
			Handler:    _RecordServer_Record_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "recordserver/record_server.proto",
}
