// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.1
// source: auth_token/auth_token_server.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AuthTokenServerClient is the client API for AuthTokenServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthTokenServerClient interface {
	GetToken(ctx context.Context, in *GetTokenRequest, opts ...grpc.CallOption) (*GetTokenResponse, error)
}

type authTokenServerClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthTokenServerClient(cc grpc.ClientConnInterface) AuthTokenServerClient {
	return &authTokenServerClient{cc}
}

func (c *authTokenServerClient) GetToken(ctx context.Context, in *GetTokenRequest, opts ...grpc.CallOption) (*GetTokenResponse, error) {
	out := new(GetTokenResponse)
	err := c.cc.Invoke(ctx, "/auth_token_server.AuthTokenServer/GetToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthTokenServerServer is the server API for AuthTokenServer service.
// All implementations must embed UnimplementedAuthTokenServerServer
// for forward compatibility
type AuthTokenServerServer interface {
	GetToken(context.Context, *GetTokenRequest) (*GetTokenResponse, error)
	mustEmbedUnimplementedAuthTokenServerServer()
}

// UnimplementedAuthTokenServerServer must be embedded to have forward compatible implementations.
type UnimplementedAuthTokenServerServer struct {
}

func (UnimplementedAuthTokenServerServer) GetToken(context.Context, *GetTokenRequest) (*GetTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetToken not implemented")
}
func (UnimplementedAuthTokenServerServer) mustEmbedUnimplementedAuthTokenServerServer() {}

// UnsafeAuthTokenServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthTokenServerServer will
// result in compilation errors.
type UnsafeAuthTokenServerServer interface {
	mustEmbedUnimplementedAuthTokenServerServer()
}

func RegisterAuthTokenServerServer(s grpc.ServiceRegistrar, srv AuthTokenServerServer) {
	s.RegisterService(&AuthTokenServer_ServiceDesc, srv)
}

func _AuthTokenServer_GetToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthTokenServerServer).GetToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth_token_server.AuthTokenServer/GetToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthTokenServerServer).GetToken(ctx, req.(*GetTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthTokenServer_ServiceDesc is the grpc.ServiceDesc for AuthTokenServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthTokenServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth_token_server.AuthTokenServer",
	HandlerType: (*AuthTokenServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetToken",
			Handler:    _AuthTokenServer_GetToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth_token/auth_token_server.proto",
}
